deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,34 +1,62 @@
 version: 2.1
 
 commands:
-  destroy_environment:
-    description: Destroy backend and frontend cloudformation stacks given a workflow ID.
+  destroy-environment:
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      workflow_id:
-        type: string
+      # Add parameter here   
     steps:
       - run:
-          name: Destroy environments
+          name: Destroy backend
           when: on_fail
           command: |
-            echo "Destroying environment: <<parameters.workflow_id>> "
-            aws cloudformation delete-stack --stack-name udapeople-backend-prod-<<parameters.workflow_id>>
-            aws s3 rm s3://udapeople-prod-<<parameters.workflow_id>> --recursive
-            aws cloudformation delete-stack --stack-name udapeople-frontend-prod-<<parameters.workflow_id>>
-  undo_migrations:
+            aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
+         #   exit 1
+      - run:
+          name: Destroy frontend
+          when: on_fail
+          command: |
+            aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
+         #   exit 1
+
+  revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
           when: on_fail
           command: |
-            cd ~/project/backend
-            if [[ -f "~/project/.circleci/outputs/db_migration_success" ]]; then
-              npm i
-              npm run migration:revert
+            SUCCESS=`curl -H "token: 8e0646c2-42b4-4733-80b0-823ba04e351e" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}`
+            echo $SUCCESS
+            if(( $SUCCESS==1 )); 
+            then
+              cd ~/project/backend
+              npm install
+              npm run migrations:revert
             fi
+
 jobs:
-  build_backend:
+  build-frontend:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
+      - run:
+          name: Build front-end
+          command: |
+            cd frontend
+            npm install
+            npm run build
+           # exit 1
+      - save_cache:
+          paths: [frontend/node_modules]
+          key: frontend-build
+
+  build-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
@@ -41,315 +69,244 @@ jobs:
             cd backend
             npm install
             npm run build
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/backend/node_modules
-            - project/*
+           # exit 1
+      - save_cache:
+          paths: [backend/node_modules] # path to save the files 
+          key: backend-build
 
-  build_frontend:
+
+  test-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - run: npm i --prefix frontend
-      - run: npm run lint --prefix frontend
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/frontend/node_modules
-
-  test_backend:
+      - restore_cache:
+          keys: [frontend-test]
+      - run: 
+          name: Run frontend test
+          command: |
+            cd frontend
+            npm install
+            npm run test
+      - save_cache:
+          paths: [frontend/node_modules] # path to save the files 
+          key: frontend-test      
+                
+  test-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - attach_workspace:
-          at: ~/
-      - run: npm i --prefix backend
-      - run: npm run test --prefix backend
+      - restore_cache:
+          keys: [backend-test]
+      - run: 
+          name: Run backend test
+          command: |
+            cd backend
+            npm install
+            npm run test
+      - save_cache:
+          paths: [backend/node_modules] # path to save the files 
+          key: backend-test 
 
-  test_frontend:
+  scan-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - attach_workspace:
-          at: ~/
-      - run: npm i --prefix frontend
-      - run: npm run test --prefix frontend
+      - restore_cache:
+          keys: [frontend-scan]
+      - run: 
+          name: Run frontend scan
+          command: |
+            cd frontend
+            npm install
+            npm audit fix --audit-level=critical --force
+            npm audit --audit-level=critical
+      - save_cache:
+          paths: [frontend/node_modules] # path to save the files 
+          key: frontend-scan 
 
-  analyze_backend:
+  scan-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - run: npm audit --audit-level=critical --prefix backend
+      - restore_cache:
+          keys: [backend-scan]
+      - run: 
+          name: Run backend scan
+          command: |
+            cd frontend
+            npm install
+            npm audit fix --audit-level=critical --force
+            npm audit --audit-level=critical
+      - save_cache:
+          paths: [backend/node_modules] # path to save the files 
+          key: backend-scan
 
-  analyze_frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - run: npm audit --audit-level=critical --prefix frontend
-
-  deploy_backend_infrastructure:
+  deploy-infrastructure:
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
+      - run: yum install -y tar gzip
       - run:
-          name: Deploy the backend infrastructure using cloudformation
+          name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              --parameter-overrides ID="prod-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --stack-name udapeople-backend-prod-${CIRCLE_WORKFLOW_ID:0:7}
-      - run: yum -y install tar gzip
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --tags project=udapeople 
+          #   exit 1
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --tags project=udapeople 
+           #   exit 1
+      - run:
+          name: Add back-end ip to ansible inventory
+          command: |
+            aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:project,Values=udapeople" \
+              --output text >> ~/project/.circleci/ansible/inventory.txt
+         # For troubleshooting   cat ~/project/.circleci/ansible/inventory.txt
+          #  exit 1
+    #  - run:
+     #     name: catch events log upon failures
+      #    when: on_fail
+       #   command: |
+        #    aws cloudformation describe-stack-events --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
+          #  exit 1
       - persist_to_workspace:
           root: ~/
           paths:
-            - project/.circleci/outputs/backend_url.txt
-            - project/.circleci/ansible/inventory.txt
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+            - project/*
+      - destroy-environment
+      # Here's where you will add some code to rollback on failure
 
-  deploy_frontend_infrastructure:
+  configure-infrastructure:
     docker:
-      - image: amazon/aws-cli
+      - image: python:3.7-alpine3.11
     steps:
       - checkout
+      - add_ssh_keys:
+          fingerprints: ["da:59:75:2c:0b:64:8d:da:99:ca:b5:aa:57:f4:80:69"]
+      - attach_workspace:
+          at: ~/
       - run:
-          name: Deploy the frontend infrastructure using cloudformation
+          name: Install dependencies
           command: |
-            aws cloudformation deploy \
-              --template-file .circleci/cloudformation/frontend_infrastructure.yml \
-              --parameter-overrides ID="prod-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --stack-name udapeople-frontend-prod-${CIRCLE_WORKFLOW_ID:0:7}
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+            apk add --update ansible
+      - run:
+          name: Configure server
+          command: |
+            cd .circleci/ansible
+            ansible-playbook -i inventory.txt configure-server.yml
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - project/*
+      - destroy-environment
+      # Here's where you will add some code to rollback on failure      
 
-  run_db_migrations_for_backend:
+  run-migrations:
     docker:
       - image: circleci/node:13.8.0
     steps:
-      - checkout
+      - checkout 
+      - restore_cache:
+          keys:
+            - frontend-build
+            - backend-build
+            - frontend-test 
+            - backend-test
+            - frontend-scan
+            - backend-scan
       - attach_workspace:
           at: ~/
       - run:
-          name: Run DB migrations
+          name: Run migrations
           command: |
+            pwd
             cd backend
-            npm run migrations >> migration_output.txt
-            cat migration_output.txt
+            pwd
+            npm install
+            if [ $? -eq 0 ]; then echo "el install 3da"; fi
+            npm run migrations > migrations_dump.txt
+         #   Run and sve the migration output
       - run:
-          name: Store migration result in a file.
+          name: Send migration results to memstash
           command: |
-            cd backend
-            if grep -q "has been executed successfully." migration_output.txt
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-              touch ~/project/.circleci/outputs/db_migration_success
+              curl -H "Content-Type: text/plain" -H "token: 8e0646c2-42b4-4733-80b0-823ba04e351e" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
             fi
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/outputs/
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment
+     # Here's where you will add some code to rollback on failure   
 
-  deploy_backend_artifact:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - checkout
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update curl nodejs npm ansible zip
-            pip install awscli
-      - run:
-          name: Build backend app
-          command: |
-            cd ~/project/backend
-            npm i
-            npm run build
-            cd dist
-            cp ../package.json .
-            zip -rq dist.zip *
-            mkdir -p ~/project/.circleci/ansible/roles/deploy_backend/files/
-            mv dist.zip ~/project/.circleci/ansible/roles/deploy_backend/files/
-      - add_ssh_keys:
-          fingerprints: [ "c8:74:5e:9c:5f:b0:d6:68:27:22:d5:1f:39:a5:a6:a5" ]
-      - run:
-          name: Setup EC2 instance & copy compiled backend to the EC2 instance
-          command: |
-            ls ~/project/.circleci/ansible/roles/deploy_backend/files/
-            cd ~/project/backend
-            ansible-galaxy install weareinteractive.environment
-            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ~/project/.circleci/ansible/inventory.txt ~/project/.circleci/ansible/playbook.yml
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
-      - undo_migrations
-
-  package_frontend_artifact:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - checkout
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update curl nodejs npm
-            pip install awscli
-      - run:
-          name: Package frontend app
-          command: |
-            export API_URL=`cat .circleci/outputs/backend_url.txt`
-            echo "API_URL: $API_URL"
-            cd ~/project/frontend
-            npm i
-            npm install typescript@rc
-            npm run build
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/frontend/dist
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
-      - undo_migrations
-
-  deploy_frontend_artifact:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update curl tar
-            pip install awscli
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Copy frontend to s3 bucket.
-          command: |
-            cd ~/project/frontend
-            aws s3 cp dist s3://udapeople-prod-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
-      - undo_migrations
-
-  smoke_test_frontend:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update curl
-            pip install awscli
-      - run:
-          name: Package frontend app
-          command: |
-            if curl -s http://udapeople-prod-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/ | grep "Welcome"
-            then
-            return 0
-            else
-            return 1
-            fi
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
-      - undo_migrations
-
-  smoke_test_backend:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Install dependencies
-          command: |
-            apk add --update curl
-            pip install awscli
-      - run:
-          name: Test backend app.
-          command: |
-            API_URL=`cat .circleci/outputs/backend_url.txt`
-            echo $API_URL
-            curl -s $API_URL/api/status
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
-      - undo_migrations
-
-
-  deploy_cloudfront_infrastructure:
+  deploy-frontend:
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
+      - attach_workspace:
+          at: ~/
       - run:
-          name: Deploy the backend infrastructure using cloudformation
+          name: Install dependencies
           command: |
-            OLD_WORKFLOW_ID=$(aws cloudformation \
-              list-exports --query "Exports[?Name==\`UdapeopleWorkflowID\`].Value" \
-              --no-paginate --output text)
-            echo "OLD_WORKFLOW_ID: $OLD_WORKFLOW_ID."
-            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-              --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-            printf '%s\n' "${STACKS[@]}"
-            aws cloudformation deploy \
-              --template-file .circleci/cloudformation/cloudfront_infrastructure.yml \
-              --parameter-overrides ID="prod-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --stack-name udapeople-prod-cloudfront
-            if printf '%s\n' "${STACKS[@]}" | grep -q "$OLD_WORKFLOW_ID"; then
-              echo "Removing previous stack"
-              aws s3 rm "s3://udapeople-${OLD_WORKFLOW_ID}" --recursive
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OLD_WORKFLOW_ID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OLD_WORKFLOW_ID}"
-            fi
-      - destroy_environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
-      - undo_migrations
+            apt-get update -y
+            apt-get install -y tar
+            apt-get install -y gzip
+            apt-get install unzip awscli -y
+            apt-get install -y python3
+            apk add --update ansible
+      - run:
+          name: Get backend url
+          command: |
+            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople")
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            cat frontend/.env
+      - run:
+          name: Deploy frontend objects
+          command: |
+            cd frontend
+            npm install
+            npm run build
+            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+      - destroy-environment
+      - revert-migrations
+      # Here's where you will add some code to rollback on failure  
 
 workflows:
-  my_workflow:
+  default:
     jobs:
-      - build_backend
-      - deploy_backend_infrastructure:
-          requires: [build_backend]
-      - run_db_migrations_for_backend:
-          requires: [deploy_backend_infrastructure]
-
-     # - build_frontend
-      #- test_backend:
-       #   requires:
-        #    - build_backend
-      #- test_frontend:
-       #   requires:
-        #    - build_frontend
-      #- analyze_backend:
-       #   requires:
-        #    - test_backend
-      #- analyze_frontend:
-       #   requires:
-        #    - test_frontend
-
-        #    - analyze_frontend
-         # filters:
-          #  branches:
-           #   only: [ master ]
-      #- deploy_frontend_infrastructure:
-       #   requires:
-        #    - analyze_backend
-         #   - analyze_frontend
-          #filters:
-           # branches:
-            #  only: [ master ]
- 
+      - build-frontend
+      - build-backend
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
+      - scan-backend:
+          requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [master]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      
